/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as ShopIndexRouteImport } from './routes/_shop.index'
import { Route as SigninResetRouteImport } from './routes/signin_.reset'
import { Route as SigninForgotRouteImport } from './routes/signin_.forgot'
import { Route as SigninCreateRouteImport } from './routes/signin_.create'
import { Route as ShopTermsRouteImport } from './routes/_shop.terms'
import { Route as ShopSupportRouteImport } from './routes/_shop.support'
import { Route as ShopPrivacyRouteImport } from './routes/_shop.privacy'
import { Route as ShopOrdersRouteImport } from './routes/_shop.orders'
import { Route as ShopHelpRouteImport } from './routes/_shop.help'
import { Route as ShopCheckoutRouteImport } from './routes/_shop.checkout'
import { Route as ShopCartRouteImport } from './routes/_shop.cart'
import { Route as ShopAccountRouteImport } from './routes/_shop.account'
import { Route as ShopStoreSlugRouteImport } from './routes/_shop.store.$slug'
import { Route as ShopOrderIdRouteImport } from './routes/_shop.order.$id'
import { Route as ShopIpIdRouteImport } from './routes/_shop.ip.$id'
import { Route as ShopBrowseSlugRouteImport } from './routes/_shop.browse.$slug'
import { Route as ShopAccountPaymentsRouteImport } from './routes/_shop.account.payments'
import { Route as ShopAccountListsRouteImport } from './routes/_shop.account.lists'
import { Route as ShopAccountAddressesRouteImport } from './routes/_shop.account.addresses'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const SigninResetRoute = SigninResetRouteImport.update({
  id: '/signin_/reset',
  path: '/signin/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninForgotRoute = SigninForgotRouteImport.update({
  id: '/signin_/forgot',
  path: '/signin/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninCreateRoute = SigninCreateRouteImport.update({
  id: '/signin_/create',
  path: '/signin/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopTermsRoute = ShopTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSupportRoute = ShopSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPrivacyRoute = ShopPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopRoute,
} as any)
const ShopHelpRoute = ShopHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const ShopStoreSlugRoute = ShopStoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrderIdRoute = ShopOrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => ShopRoute,
} as any)
const ShopIpIdRoute = ShopIpIdRouteImport.update({
  id: '/ip/$id',
  path: '/ip/$id',
  getParentRoute: () => ShopRoute,
} as any)
const ShopBrowseSlugRoute = ShopBrowseSlugRouteImport.update({
  id: '/browse/$slug',
  path: '/browse/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountPaymentsRoute = ShopAccountPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountListsRoute = ShopAccountListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountAddressesRoute = ShopAccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => ShopAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/signin': typeof SigninRoute
  '/account': typeof ShopAccountRouteWithChildren
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/help': typeof ShopHelpRoute
  '/orders': typeof ShopOrdersRoute
  '/privacy': typeof ShopPrivacyRoute
  '/support': typeof ShopSupportRoute
  '/terms': typeof ShopTermsRoute
  '/signin/create': typeof SigninCreateRoute
  '/signin/forgot': typeof SigninForgotRoute
  '/signin/reset': typeof SigninResetRoute
  '/account/addresses': typeof ShopAccountAddressesRoute
  '/account/lists': typeof ShopAccountListsRoute
  '/account/payments': typeof ShopAccountPaymentsRoute
  '/browse/$slug': typeof ShopBrowseSlugRoute
  '/ip/$id': typeof ShopIpIdRoute
  '/order/$id': typeof ShopOrderIdRoute
  '/store/$slug': typeof ShopStoreSlugRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/account': typeof ShopAccountRouteWithChildren
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/help': typeof ShopHelpRoute
  '/orders': typeof ShopOrdersRoute
  '/privacy': typeof ShopPrivacyRoute
  '/support': typeof ShopSupportRoute
  '/terms': typeof ShopTermsRoute
  '/signin/create': typeof SigninCreateRoute
  '/signin/forgot': typeof SigninForgotRoute
  '/signin/reset': typeof SigninResetRoute
  '/': typeof ShopIndexRoute
  '/account/addresses': typeof ShopAccountAddressesRoute
  '/account/lists': typeof ShopAccountListsRoute
  '/account/payments': typeof ShopAccountPaymentsRoute
  '/browse/$slug': typeof ShopBrowseSlugRoute
  '/ip/$id': typeof ShopIpIdRoute
  '/order/$id': typeof ShopOrderIdRoute
  '/store/$slug': typeof ShopStoreSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteWithChildren
  '/signin': typeof SigninRoute
  '/_shop/account': typeof ShopAccountRouteWithChildren
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/help': typeof ShopHelpRoute
  '/_shop/orders': typeof ShopOrdersRoute
  '/_shop/privacy': typeof ShopPrivacyRoute
  '/_shop/support': typeof ShopSupportRoute
  '/_shop/terms': typeof ShopTermsRoute
  '/signin_/create': typeof SigninCreateRoute
  '/signin_/forgot': typeof SigninForgotRoute
  '/signin_/reset': typeof SigninResetRoute
  '/_shop/': typeof ShopIndexRoute
  '/_shop/account/addresses': typeof ShopAccountAddressesRoute
  '/_shop/account/lists': typeof ShopAccountListsRoute
  '/_shop/account/payments': typeof ShopAccountPaymentsRoute
  '/_shop/browse/$slug': typeof ShopBrowseSlugRoute
  '/_shop/ip/$id': typeof ShopIpIdRoute
  '/_shop/order/$id': typeof ShopOrderIdRoute
  '/_shop/store/$slug': typeof ShopStoreSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/orders'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/signin/create'
    | '/signin/forgot'
    | '/signin/reset'
    | '/account/addresses'
    | '/account/lists'
    | '/account/payments'
    | '/browse/$slug'
    | '/ip/$id'
    | '/order/$id'
    | '/store/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/orders'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/signin/create'
    | '/signin/forgot'
    | '/signin/reset'
    | '/'
    | '/account/addresses'
    | '/account/lists'
    | '/account/payments'
    | '/browse/$slug'
    | '/ip/$id'
    | '/order/$id'
    | '/store/$slug'
  id:
    | '__root__'
    | '/_shop'
    | '/signin'
    | '/_shop/account'
    | '/_shop/cart'
    | '/_shop/checkout'
    | '/_shop/help'
    | '/_shop/orders'
    | '/_shop/privacy'
    | '/_shop/support'
    | '/_shop/terms'
    | '/signin_/create'
    | '/signin_/forgot'
    | '/signin_/reset'
    | '/_shop/'
    | '/_shop/account/addresses'
    | '/_shop/account/lists'
    | '/_shop/account/payments'
    | '/_shop/browse/$slug'
    | '/_shop/ip/$id'
    | '/_shop/order/$id'
    | '/_shop/store/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRoute: typeof ShopRouteWithChildren
  SigninRoute: typeof SigninRoute
  SigninCreateRoute: typeof SigninCreateRoute
  SigninForgotRoute: typeof SigninForgotRoute
  SigninResetRoute: typeof SigninResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/signin_/reset': {
      id: '/signin_/reset'
      path: '/signin/reset'
      fullPath: '/signin/reset'
      preLoaderRoute: typeof SigninResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin_/forgot': {
      id: '/signin_/forgot'
      path: '/signin/forgot'
      fullPath: '/signin/forgot'
      preLoaderRoute: typeof SigninForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin_/create': {
      id: '/signin_/create'
      path: '/signin/create'
      fullPath: '/signin/create'
      preLoaderRoute: typeof SigninCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/terms': {
      id: '/_shop/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof ShopTermsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/support': {
      id: '/_shop/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof ShopSupportRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/privacy': {
      id: '/_shop/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof ShopPrivacyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/orders': {
      id: '/_shop/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/help': {
      id: '/_shop/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ShopHelpRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/account': {
      id: '/_shop/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/store/$slug': {
      id: '/_shop/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof ShopStoreSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/order/$id': {
      id: '/_shop/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof ShopOrderIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/ip/$id': {
      id: '/_shop/ip/$id'
      path: '/ip/$id'
      fullPath: '/ip/$id'
      preLoaderRoute: typeof ShopIpIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/browse/$slug': {
      id: '/_shop/browse/$slug'
      path: '/browse/$slug'
      fullPath: '/browse/$slug'
      preLoaderRoute: typeof ShopBrowseSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/account/payments': {
      id: '/_shop/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof ShopAccountPaymentsRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/_shop/account/lists': {
      id: '/_shop/account/lists'
      path: '/lists'
      fullPath: '/account/lists'
      preLoaderRoute: typeof ShopAccountListsRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/_shop/account/addresses': {
      id: '/_shop/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof ShopAccountAddressesRouteImport
      parentRoute: typeof ShopAccountRoute
    }
  }
}

interface ShopAccountRouteChildren {
  ShopAccountAddressesRoute: typeof ShopAccountAddressesRoute
  ShopAccountListsRoute: typeof ShopAccountListsRoute
  ShopAccountPaymentsRoute: typeof ShopAccountPaymentsRoute
}

const ShopAccountRouteChildren: ShopAccountRouteChildren = {
  ShopAccountAddressesRoute: ShopAccountAddressesRoute,
  ShopAccountListsRoute: ShopAccountListsRoute,
  ShopAccountPaymentsRoute: ShopAccountPaymentsRoute,
}

const ShopAccountRouteWithChildren = ShopAccountRoute._addFileChildren(
  ShopAccountRouteChildren,
)

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRouteWithChildren
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopHelpRoute: typeof ShopHelpRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopPrivacyRoute: typeof ShopPrivacyRoute
  ShopSupportRoute: typeof ShopSupportRoute
  ShopTermsRoute: typeof ShopTermsRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopBrowseSlugRoute: typeof ShopBrowseSlugRoute
  ShopIpIdRoute: typeof ShopIpIdRoute
  ShopOrderIdRoute: typeof ShopOrderIdRoute
  ShopStoreSlugRoute: typeof ShopStoreSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRouteWithChildren,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopHelpRoute: ShopHelpRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopPrivacyRoute: ShopPrivacyRoute,
  ShopSupportRoute: ShopSupportRoute,
  ShopTermsRoute: ShopTermsRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopBrowseSlugRoute: ShopBrowseSlugRoute,
  ShopIpIdRoute: ShopIpIdRoute,
  ShopOrderIdRoute: ShopOrderIdRoute,
  ShopStoreSlugRoute: ShopStoreSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShopRoute: ShopRouteWithChildren,
  SigninRoute: SigninRoute,
  SigninCreateRoute: SigninCreateRoute,
  SigninForgotRoute: SigninForgotRoute,
  SigninResetRoute: SigninResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
