kind = "web"
previewPath = "/"
title = "Alkemart"
version = "1.0.0"
id = "artifacts/alkemart"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24668

[services.development]
run = "pnpm --filter @workspace/alkemart run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/alkemart", "run", "build" ]
serve = "static"
publicDir = "artifacts/alkemart/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24668"
BASE_PATH = "/"
