/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as ShopsSlugRouteImport } from './routes/shops.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as CheckoutPendingRouteImport } from './routes/checkout.pending'
import { Route as CheckoutCardCallbackRouteImport } from './routes/checkout.card-callback'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BrowseSlugRouteImport } from './routes/browse.$slug'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as OrderIdReturnRouteImport } from './routes/order.$id.return'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsSlugRoute = ShopsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopsRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPendingRoute = CheckoutPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutCardCallbackRoute = CheckoutCardCallbackRouteImport.update({
  id: '/card-callback',
  path: '/card-callback',
  getParentRoute: () => CheckoutRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSlugRoute = BrowseSlugRouteImport.update({
  id: '/browse/$slug',
  path: '/browse/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const OrderIdReturnRoute = OrderIdReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => OrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/partners': typeof PartnersRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/sellers': typeof SellersRoute
  '/shops': typeof ShopsRouteWithChildren
  '/signin': typeof SigninRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/browse/$slug': typeof BrowseSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/card-callback': typeof CheckoutCardCallbackRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/order/$id/return': typeof OrderIdReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/partners': typeof PartnersRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/sellers': typeof SellersRoute
  '/shops': typeof ShopsRouteWithChildren
  '/signin': typeof SigninRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/browse/$slug': typeof BrowseSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/card-callback': typeof CheckoutCardCallbackRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/order/$id/return': typeof OrderIdReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/partners': typeof PartnersRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/sellers': typeof SellersRoute
  '/shops': typeof ShopsRouteWithChildren
  '/signin': typeof SigninRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/browse/$slug': typeof BrowseSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/card-callback': typeof CheckoutCardCallbackRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/order/$id/return': typeof OrderIdReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/help'
    | '/login'
    | '/orders'
    | '/partners'
    | '/search'
    | '/sell'
    | '/sellers'
    | '/shops'
    | '/signin'
    | '/account/wishlist'
    | '/browse/$slug'
    | '/categories/$slug'
    | '/checkout/card-callback'
    | '/checkout/pending'
    | '/order/$id'
    | '/product/$id'
    | '/shops/$slug'
    | '/store/$slug'
    | '/order/$id/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/help'
    | '/login'
    | '/orders'
    | '/partners'
    | '/search'
    | '/sell'
    | '/sellers'
    | '/shops'
    | '/signin'
    | '/account/wishlist'
    | '/browse/$slug'
    | '/categories/$slug'
    | '/checkout/card-callback'
    | '/checkout/pending'
    | '/order/$id'
    | '/product/$id'
    | '/shops/$slug'
    | '/store/$slug'
    | '/order/$id/return'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/delivery'
    | '/help'
    | '/login'
    | '/orders'
    | '/partners'
    | '/search'
    | '/sell'
    | '/sellers'
    | '/shops'
    | '/signin'
    | '/account/wishlist'
    | '/browse/$slug'
    | '/categories/$slug'
    | '/checkout/card-callback'
    | '/checkout/pending'
    | '/order/$id'
    | '/product/$id'
    | '/shops/$slug'
    | '/store/$slug'
    | '/order/$id/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PartnersRoute: typeof PartnersRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  SellersRoute: typeof SellersRoute
  ShopsRoute: typeof ShopsRouteWithChildren
  SigninRoute: typeof SigninRoute
  BrowseSlugRoute: typeof BrowseSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  OrderIdRoute: typeof OrderIdRouteWithChildren
  ProductIdRoute: typeof ProductIdRoute
  StoreSlugRoute: typeof StoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$slug': {
      id: '/shops/$slug'
      path: '/$slug'
      fullPath: '/shops/$slug'
      preLoaderRoute: typeof ShopsSlugRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pending': {
      id: '/checkout/pending'
      path: '/pending'
      fullPath: '/checkout/pending'
      preLoaderRoute: typeof CheckoutPendingRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/card-callback': {
      id: '/checkout/card-callback'
      path: '/card-callback'
      fullPath: '/checkout/card-callback'
      preLoaderRoute: typeof CheckoutCardCallbackRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$slug': {
      id: '/browse/$slug'
      path: '/browse/$slug'
      fullPath: '/browse/$slug'
      preLoaderRoute: typeof BrowseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/order/$id/return': {
      id: '/order/$id/return'
      path: '/return'
      fullPath: '/order/$id/return'
      preLoaderRoute: typeof OrderIdReturnRouteImport
      parentRoute: typeof OrderIdRoute
    }
  }
}

interface AccountRouteChildren {
  AccountWishlistRoute: typeof AccountWishlistRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountWishlistRoute: AccountWishlistRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CheckoutRouteChildren {
  CheckoutCardCallbackRoute: typeof CheckoutCardCallbackRoute
  CheckoutPendingRoute: typeof CheckoutPendingRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCardCallbackRoute: CheckoutCardCallbackRoute,
  CheckoutPendingRoute: CheckoutPendingRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ShopsRouteChildren {
  ShopsSlugRoute: typeof ShopsSlugRoute
}

const ShopsRouteChildren: ShopsRouteChildren = {
  ShopsSlugRoute: ShopsSlugRoute,
}

const ShopsRouteWithChildren = ShopsRoute._addFileChildren(ShopsRouteChildren)

interface OrderIdRouteChildren {
  OrderIdReturnRoute: typeof OrderIdReturnRoute
}

const OrderIdRouteChildren: OrderIdRouteChildren = {
  OrderIdReturnRoute: OrderIdReturnRoute,
}

const OrderIdRouteWithChildren =
  OrderIdRoute._addFileChildren(OrderIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PartnersRoute: PartnersRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  SellersRoute: SellersRoute,
  ShopsRoute: ShopsRouteWithChildren,
  SigninRoute: SigninRoute,
  BrowseSlugRoute: BrowseSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  OrderIdRoute: OrderIdRouteWithChildren,
  ProductIdRoute: ProductIdRoute,
  StoreSlugRoute: StoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
