/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppMoneyRouteImport } from './routes/_app/money'
import { Route as AppShopRouteImport } from './routes/_app/shop'
import { Route as AppBusinessIndexRouteImport } from './routes/_app/business.index'
import { Route as AppMessagesIndexRouteImport } from './routes/_app/messages.index'
import { Route as AppMessagesIdRouteImport } from './routes/_app/messages.$id'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders.index'
import { Route as AppOrdersIdRouteImport } from './routes/_app/orders.$id'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products.index'
import { Route as AppProductsIdRouteImport } from './routes/_app/products.$id'
import { Route as AppProductsNewRouteImport } from './routes/_app/products.new'
import { Route as AppBusinessStatementsPeriodRouteImport } from './routes/_app/business.statements.$period'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyRoute = AppMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessIndexRoute = AppBusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIdRoute = AppMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessStatementsPeriodRoute =
  AppBusinessStatementsPeriodRouteImport.update({
    id: '/business/statements/$period',
    path: '/business/statements/$period',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/account': typeof AppAccountRoute
  '/money': typeof AppMoneyRoute
  '/shop': typeof AppShopRoute
  '/messages/$id': typeof AppMessagesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/business/': typeof AppBusinessIndexRoute
  '/messages/': typeof AppMessagesIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/business/statements/$period': typeof AppBusinessStatementsPeriodRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/account': typeof AppAccountRoute
  '/money': typeof AppMoneyRoute
  '/shop': typeof AppShopRoute
  '/': typeof AppIndexRoute
  '/messages/$id': typeof AppMessagesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/business': typeof AppBusinessIndexRoute
  '/messages': typeof AppMessagesIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/business/statements/$period': typeof AppBusinessStatementsPeriodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/money': typeof AppMoneyRoute
  '/_app/shop': typeof AppShopRoute
  '/_app/': typeof AppIndexRoute
  '/_app/messages/$id': typeof AppMessagesIdRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/products/$id': typeof AppProductsIdRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/business/': typeof AppBusinessIndexRoute
  '/_app/messages/': typeof AppMessagesIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/business/statements/$period': typeof AppBusinessStatementsPeriodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/account'
    | '/money'
    | '/shop'
    | '/messages/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/products/new'
    | '/business/'
    | '/messages/'
    | '/orders/'
    | '/products/'
    | '/business/statements/$period'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/setup'
    | '/account'
    | '/money'
    | '/shop'
    | '/'
    | '/messages/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/products/new'
    | '/business'
    | '/messages'
    | '/orders'
    | '/products'
    | '/business/statements/$period'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/setup'
    | '/_app/account'
    | '/_app/money'
    | '/_app/shop'
    | '/_app/'
    | '/_app/messages/$id'
    | '/_app/orders/$id'
    | '/_app/products/$id'
    | '/_app/products/new'
    | '/_app/business/'
    | '/_app/messages/'
    | '/_app/orders/'
    | '/_app/products/'
    | '/_app/business/statements/$period'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money': {
      id: '/_app/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AppMoneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business/': {
      id: '/_app/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof AppBusinessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/': {
      id: '/_app/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/$id': {
      id: '/_app/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AppMessagesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business/statements/$period': {
      id: '/_app/business/statements/$period'
      path: '/business/statements/$period'
      fullPath: '/business/statements/$period'
      preLoaderRoute: typeof AppBusinessStatementsPeriodRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppMoneyRoute: typeof AppMoneyRoute
  AppShopRoute: typeof AppShopRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMessagesIdRoute: typeof AppMessagesIdRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppBusinessIndexRoute: typeof AppBusinessIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppBusinessStatementsPeriodRoute: typeof AppBusinessStatementsPeriodRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppMoneyRoute: AppMoneyRoute,
  AppShopRoute: AppShopRoute,
  AppIndexRoute: AppIndexRoute,
  AppMessagesIdRoute: AppMessagesIdRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppProductsIdRoute: AppProductsIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppBusinessIndexRoute: AppBusinessIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppBusinessStatementsPeriodRoute: AppBusinessStatementsPeriodRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
