/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as ShopIndexRouteImport } from './routes/_shop.index'
import { Route as SigninCreateRouteImport } from './routes/signin_.create'
import { Route as ShopVendorRouteImport } from './routes/_shop.vendor'
import { Route as ShopTermsRouteImport } from './routes/_shop.terms'
import { Route as ShopSupportRouteImport } from './routes/_shop.support'
import { Route as ShopPrivacyRouteImport } from './routes/_shop.privacy'
import { Route as ShopOrdersRouteImport } from './routes/_shop.orders'
import { Route as ShopHelpRouteImport } from './routes/_shop.help'
import { Route as ShopCheckoutRouteImport } from './routes/_shop.checkout'
import { Route as ShopCartRouteImport } from './routes/_shop.cart'
import { Route as ShopAdminRouteImport } from './routes/_shop.admin'
import { Route as ShopAccountRouteImport } from './routes/_shop.account'
import { Route as ShopVendorStoreRouteImport } from './routes/_shop.vendor.store'
import { Route as ShopVendorProductsRouteImport } from './routes/_shop.vendor.products'
import { Route as ShopVendorOrdersRouteImport } from './routes/_shop.vendor.orders'
import { Route as ShopVendorMessagesRouteImport } from './routes/_shop.vendor.messages'
import { Route as ShopStoreSlugRouteImport } from './routes/_shop.store.$slug'
import { Route as ShopOrderIdRouteImport } from './routes/_shop.order.$id'
import { Route as ShopIpIdRouteImport } from './routes/_shop.ip.$id'
import { Route as ShopBrowseSlugRouteImport } from './routes/_shop.browse.$slug'
import { Route as ShopAdminVendorsRouteImport } from './routes/_shop.admin.vendors'
import { Route as ShopAdminPromotionsRouteImport } from './routes/_shop.admin.promotions'
import { Route as ShopAdminInboxRouteImport } from './routes/_shop.admin.inbox'
import { Route as ShopAdminImagesRouteImport } from './routes/_shop.admin.images'
import { Route as ShopAdminHomepageRouteImport } from './routes/_shop.admin.homepage'
import { Route as ShopAdminDisputesRouteImport } from './routes/_shop.admin.disputes'
import { Route as ShopAccountPaymentsRouteImport } from './routes/_shop.account.payments'
import { Route as ShopAccountListsRouteImport } from './routes/_shop.account.lists'
import { Route as ShopAccountAddressesRouteImport } from './routes/_shop.account.addresses'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const SigninCreateRoute = SigninCreateRouteImport.update({
  id: '/signin_/create',
  path: '/signin/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopVendorRoute = ShopVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => ShopRoute,
} as any)
const ShopTermsRoute = ShopTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSupportRoute = ShopSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPrivacyRoute = ShopPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopRoute,
} as any)
const ShopHelpRoute = ShopHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAdminRoute = ShopAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const ShopVendorStoreRoute = ShopVendorStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => ShopVendorRoute,
} as any)
const ShopVendorProductsRoute = ShopVendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShopVendorRoute,
} as any)
const ShopVendorOrdersRoute = ShopVendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopVendorRoute,
} as any)
const ShopVendorMessagesRoute = ShopVendorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ShopVendorRoute,
} as any)
const ShopStoreSlugRoute = ShopStoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrderIdRoute = ShopOrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => ShopRoute,
} as any)
const ShopIpIdRoute = ShopIpIdRouteImport.update({
  id: '/ip/$id',
  path: '/ip/$id',
  getParentRoute: () => ShopRoute,
} as any)
const ShopBrowseSlugRoute = ShopBrowseSlugRouteImport.update({
  id: '/browse/$slug',
  path: '/browse/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAdminVendorsRoute = ShopAdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAdminPromotionsRoute = ShopAdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAdminInboxRoute = ShopAdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAdminImagesRoute = ShopAdminImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAdminHomepageRoute = ShopAdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAdminDisputesRoute = ShopAdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => ShopAdminRoute,
} as any)
const ShopAccountPaymentsRoute = ShopAccountPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountListsRoute = ShopAccountListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountAddressesRoute = ShopAccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => ShopAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/signin': typeof SigninRoute
  '/account': typeof ShopAccountRouteWithChildren
  '/admin': typeof ShopAdminRouteWithChildren
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/help': typeof ShopHelpRoute
  '/orders': typeof ShopOrdersRoute
  '/privacy': typeof ShopPrivacyRoute
  '/support': typeof ShopSupportRoute
  '/terms': typeof ShopTermsRoute
  '/vendor': typeof ShopVendorRouteWithChildren
  '/signin/create': typeof SigninCreateRoute
  '/account/addresses': typeof ShopAccountAddressesRoute
  '/account/lists': typeof ShopAccountListsRoute
  '/account/payments': typeof ShopAccountPaymentsRoute
  '/admin/disputes': typeof ShopAdminDisputesRoute
  '/admin/homepage': typeof ShopAdminHomepageRoute
  '/admin/images': typeof ShopAdminImagesRoute
  '/admin/inbox': typeof ShopAdminInboxRoute
  '/admin/promotions': typeof ShopAdminPromotionsRoute
  '/admin/vendors': typeof ShopAdminVendorsRoute
  '/browse/$slug': typeof ShopBrowseSlugRoute
  '/ip/$id': typeof ShopIpIdRoute
  '/order/$id': typeof ShopOrderIdRoute
  '/store/$slug': typeof ShopStoreSlugRoute
  '/vendor/messages': typeof ShopVendorMessagesRoute
  '/vendor/orders': typeof ShopVendorOrdersRoute
  '/vendor/products': typeof ShopVendorProductsRoute
  '/vendor/store': typeof ShopVendorStoreRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/account': typeof ShopAccountRouteWithChildren
  '/admin': typeof ShopAdminRouteWithChildren
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/help': typeof ShopHelpRoute
  '/orders': typeof ShopOrdersRoute
  '/privacy': typeof ShopPrivacyRoute
  '/support': typeof ShopSupportRoute
  '/terms': typeof ShopTermsRoute
  '/vendor': typeof ShopVendorRouteWithChildren
  '/signin/create': typeof SigninCreateRoute
  '/': typeof ShopIndexRoute
  '/account/addresses': typeof ShopAccountAddressesRoute
  '/account/lists': typeof ShopAccountListsRoute
  '/account/payments': typeof ShopAccountPaymentsRoute
  '/admin/disputes': typeof ShopAdminDisputesRoute
  '/admin/homepage': typeof ShopAdminHomepageRoute
  '/admin/images': typeof ShopAdminImagesRoute
  '/admin/inbox': typeof ShopAdminInboxRoute
  '/admin/promotions': typeof ShopAdminPromotionsRoute
  '/admin/vendors': typeof ShopAdminVendorsRoute
  '/browse/$slug': typeof ShopBrowseSlugRoute
  '/ip/$id': typeof ShopIpIdRoute
  '/order/$id': typeof ShopOrderIdRoute
  '/store/$slug': typeof ShopStoreSlugRoute
  '/vendor/messages': typeof ShopVendorMessagesRoute
  '/vendor/orders': typeof ShopVendorOrdersRoute
  '/vendor/products': typeof ShopVendorProductsRoute
  '/vendor/store': typeof ShopVendorStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteWithChildren
  '/signin': typeof SigninRoute
  '/_shop/account': typeof ShopAccountRouteWithChildren
  '/_shop/admin': typeof ShopAdminRouteWithChildren
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/help': typeof ShopHelpRoute
  '/_shop/orders': typeof ShopOrdersRoute
  '/_shop/privacy': typeof ShopPrivacyRoute
  '/_shop/support': typeof ShopSupportRoute
  '/_shop/terms': typeof ShopTermsRoute
  '/_shop/vendor': typeof ShopVendorRouteWithChildren
  '/signin_/create': typeof SigninCreateRoute
  '/_shop/': typeof ShopIndexRoute
  '/_shop/account/addresses': typeof ShopAccountAddressesRoute
  '/_shop/account/lists': typeof ShopAccountListsRoute
  '/_shop/account/payments': typeof ShopAccountPaymentsRoute
  '/_shop/admin/disputes': typeof ShopAdminDisputesRoute
  '/_shop/admin/homepage': typeof ShopAdminHomepageRoute
  '/_shop/admin/images': typeof ShopAdminImagesRoute
  '/_shop/admin/inbox': typeof ShopAdminInboxRoute
  '/_shop/admin/promotions': typeof ShopAdminPromotionsRoute
  '/_shop/admin/vendors': typeof ShopAdminVendorsRoute
  '/_shop/browse/$slug': typeof ShopBrowseSlugRoute
  '/_shop/ip/$id': typeof ShopIpIdRoute
  '/_shop/order/$id': typeof ShopOrderIdRoute
  '/_shop/store/$slug': typeof ShopStoreSlugRoute
  '/_shop/vendor/messages': typeof ShopVendorMessagesRoute
  '/_shop/vendor/orders': typeof ShopVendorOrdersRoute
  '/_shop/vendor/products': typeof ShopVendorProductsRoute
  '/_shop/vendor/store': typeof ShopVendorStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/orders'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/vendor'
    | '/signin/create'
    | '/account/addresses'
    | '/account/lists'
    | '/account/payments'
    | '/admin/disputes'
    | '/admin/homepage'
    | '/admin/images'
    | '/admin/inbox'
    | '/admin/promotions'
    | '/admin/vendors'
    | '/browse/$slug'
    | '/ip/$id'
    | '/order/$id'
    | '/store/$slug'
    | '/vendor/messages'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/help'
    | '/orders'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/vendor'
    | '/signin/create'
    | '/'
    | '/account/addresses'
    | '/account/lists'
    | '/account/payments'
    | '/admin/disputes'
    | '/admin/homepage'
    | '/admin/images'
    | '/admin/inbox'
    | '/admin/promotions'
    | '/admin/vendors'
    | '/browse/$slug'
    | '/ip/$id'
    | '/order/$id'
    | '/store/$slug'
    | '/vendor/messages'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/store'
  id:
    | '__root__'
    | '/_shop'
    | '/signin'
    | '/_shop/account'
    | '/_shop/admin'
    | '/_shop/cart'
    | '/_shop/checkout'
    | '/_shop/help'
    | '/_shop/orders'
    | '/_shop/privacy'
    | '/_shop/support'
    | '/_shop/terms'
    | '/_shop/vendor'
    | '/signin_/create'
    | '/_shop/'
    | '/_shop/account/addresses'
    | '/_shop/account/lists'
    | '/_shop/account/payments'
    | '/_shop/admin/disputes'
    | '/_shop/admin/homepage'
    | '/_shop/admin/images'
    | '/_shop/admin/inbox'
    | '/_shop/admin/promotions'
    | '/_shop/admin/vendors'
    | '/_shop/browse/$slug'
    | '/_shop/ip/$id'
    | '/_shop/order/$id'
    | '/_shop/store/$slug'
    | '/_shop/vendor/messages'
    | '/_shop/vendor/orders'
    | '/_shop/vendor/products'
    | '/_shop/vendor/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRoute: typeof ShopRouteWithChildren
  SigninRoute: typeof SigninRoute
  SigninCreateRoute: typeof SigninCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/signin_/create': {
      id: '/signin_/create'
      path: '/signin/create'
      fullPath: '/signin/create'
      preLoaderRoute: typeof SigninCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/vendor': {
      id: '/_shop/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof ShopVendorRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/terms': {
      id: '/_shop/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof ShopTermsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/support': {
      id: '/_shop/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof ShopSupportRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/privacy': {
      id: '/_shop/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof ShopPrivacyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/orders': {
      id: '/_shop/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/help': {
      id: '/_shop/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ShopHelpRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/admin': {
      id: '/_shop/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ShopAdminRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/account': {
      id: '/_shop/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/vendor/store': {
      id: '/_shop/vendor/store'
      path: '/store'
      fullPath: '/vendor/store'
      preLoaderRoute: typeof ShopVendorStoreRouteImport
      parentRoute: typeof ShopVendorRoute
    }
    '/_shop/vendor/products': {
      id: '/_shop/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof ShopVendorProductsRouteImport
      parentRoute: typeof ShopVendorRoute
    }
    '/_shop/vendor/orders': {
      id: '/_shop/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof ShopVendorOrdersRouteImport
      parentRoute: typeof ShopVendorRoute
    }
    '/_shop/vendor/messages': {
      id: '/_shop/vendor/messages'
      path: '/messages'
      fullPath: '/vendor/messages'
      preLoaderRoute: typeof ShopVendorMessagesRouteImport
      parentRoute: typeof ShopVendorRoute
    }
    '/_shop/store/$slug': {
      id: '/_shop/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof ShopStoreSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/order/$id': {
      id: '/_shop/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof ShopOrderIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/ip/$id': {
      id: '/_shop/ip/$id'
      path: '/ip/$id'
      fullPath: '/ip/$id'
      preLoaderRoute: typeof ShopIpIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/browse/$slug': {
      id: '/_shop/browse/$slug'
      path: '/browse/$slug'
      fullPath: '/browse/$slug'
      preLoaderRoute: typeof ShopBrowseSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/admin/vendors': {
      id: '/_shop/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof ShopAdminVendorsRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/_shop/admin/promotions': {
      id: '/_shop/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof ShopAdminPromotionsRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/_shop/admin/inbox': {
      id: '/_shop/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof ShopAdminInboxRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/_shop/admin/images': {
      id: '/_shop/admin/images'
      path: '/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof ShopAdminImagesRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/_shop/admin/homepage': {
      id: '/_shop/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof ShopAdminHomepageRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/_shop/admin/disputes': {
      id: '/_shop/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof ShopAdminDisputesRouteImport
      parentRoute: typeof ShopAdminRoute
    }
    '/_shop/account/payments': {
      id: '/_shop/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof ShopAccountPaymentsRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/_shop/account/lists': {
      id: '/_shop/account/lists'
      path: '/lists'
      fullPath: '/account/lists'
      preLoaderRoute: typeof ShopAccountListsRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/_shop/account/addresses': {
      id: '/_shop/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof ShopAccountAddressesRouteImport
      parentRoute: typeof ShopAccountRoute
    }
  }
}

interface ShopAccountRouteChildren {
  ShopAccountAddressesRoute: typeof ShopAccountAddressesRoute
  ShopAccountListsRoute: typeof ShopAccountListsRoute
  ShopAccountPaymentsRoute: typeof ShopAccountPaymentsRoute
}

const ShopAccountRouteChildren: ShopAccountRouteChildren = {
  ShopAccountAddressesRoute: ShopAccountAddressesRoute,
  ShopAccountListsRoute: ShopAccountListsRoute,
  ShopAccountPaymentsRoute: ShopAccountPaymentsRoute,
}

const ShopAccountRouteWithChildren = ShopAccountRoute._addFileChildren(
  ShopAccountRouteChildren,
)

interface ShopAdminRouteChildren {
  ShopAdminDisputesRoute: typeof ShopAdminDisputesRoute
  ShopAdminHomepageRoute: typeof ShopAdminHomepageRoute
  ShopAdminImagesRoute: typeof ShopAdminImagesRoute
  ShopAdminInboxRoute: typeof ShopAdminInboxRoute
  ShopAdminPromotionsRoute: typeof ShopAdminPromotionsRoute
  ShopAdminVendorsRoute: typeof ShopAdminVendorsRoute
}

const ShopAdminRouteChildren: ShopAdminRouteChildren = {
  ShopAdminDisputesRoute: ShopAdminDisputesRoute,
  ShopAdminHomepageRoute: ShopAdminHomepageRoute,
  ShopAdminImagesRoute: ShopAdminImagesRoute,
  ShopAdminInboxRoute: ShopAdminInboxRoute,
  ShopAdminPromotionsRoute: ShopAdminPromotionsRoute,
  ShopAdminVendorsRoute: ShopAdminVendorsRoute,
}

const ShopAdminRouteWithChildren = ShopAdminRoute._addFileChildren(
  ShopAdminRouteChildren,
)

interface ShopVendorRouteChildren {
  ShopVendorMessagesRoute: typeof ShopVendorMessagesRoute
  ShopVendorOrdersRoute: typeof ShopVendorOrdersRoute
  ShopVendorProductsRoute: typeof ShopVendorProductsRoute
  ShopVendorStoreRoute: typeof ShopVendorStoreRoute
}

const ShopVendorRouteChildren: ShopVendorRouteChildren = {
  ShopVendorMessagesRoute: ShopVendorMessagesRoute,
  ShopVendorOrdersRoute: ShopVendorOrdersRoute,
  ShopVendorProductsRoute: ShopVendorProductsRoute,
  ShopVendorStoreRoute: ShopVendorStoreRoute,
}

const ShopVendorRouteWithChildren = ShopVendorRoute._addFileChildren(
  ShopVendorRouteChildren,
)

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRouteWithChildren
  ShopAdminRoute: typeof ShopAdminRouteWithChildren
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopHelpRoute: typeof ShopHelpRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopPrivacyRoute: typeof ShopPrivacyRoute
  ShopSupportRoute: typeof ShopSupportRoute
  ShopTermsRoute: typeof ShopTermsRoute
  ShopVendorRoute: typeof ShopVendorRouteWithChildren
  ShopIndexRoute: typeof ShopIndexRoute
  ShopBrowseSlugRoute: typeof ShopBrowseSlugRoute
  ShopIpIdRoute: typeof ShopIpIdRoute
  ShopOrderIdRoute: typeof ShopOrderIdRoute
  ShopStoreSlugRoute: typeof ShopStoreSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRouteWithChildren,
  ShopAdminRoute: ShopAdminRouteWithChildren,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopHelpRoute: ShopHelpRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopPrivacyRoute: ShopPrivacyRoute,
  ShopSupportRoute: ShopSupportRoute,
  ShopTermsRoute: ShopTermsRoute,
  ShopVendorRoute: ShopVendorRouteWithChildren,
  ShopIndexRoute: ShopIndexRoute,
  ShopBrowseSlugRoute: ShopBrowseSlugRoute,
  ShopIpIdRoute: ShopIpIdRoute,
  ShopOrderIdRoute: ShopOrderIdRoute,
  ShopStoreSlugRoute: ShopStoreSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShopRoute: ShopRouteWithChildren,
  SigninRoute: SigninRoute,
  SigninCreateRoute: SigninCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
