/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AccountAddressesRouteImport } from './routes/account_.addresses'
import { Route as AccountSettingsRouteImport } from './routes/account_.settings'
import { Route as AccountWishlistRouteImport } from './routes/account_.wishlist'
import { Route as BrowseSlugRouteImport } from './routes/browse.$slug'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CheckoutCardCallbackRouteImport } from './routes/checkout.card-callback'
import { Route as CheckoutPendingRouteImport } from './routes/checkout.pending'
import { Route as CompareIdRouteImport } from './routes/compare.$id'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as MessagesNewRouteImport } from './routes/messages.new'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ShopsIndexRouteImport } from './routes/shops.index'
import { Route as ShopsSlugRouteImport } from './routes/shops.$slug'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as OrderIdReturnRouteImport } from './routes/order.$id.return'
import { Route as ShopsCollectionsCollectionIdRouteImport } from './routes/shops.collections.$collectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/account_/addresses',
  path: '/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account_/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/account_/wishlist',
  path: '/account/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseSlugRoute = BrowseSlugRouteImport.update({
  id: '/browse/$slug',
  path: '/browse/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCardCallbackRoute = CheckoutCardCallbackRouteImport.update({
  id: '/checkout/card-callback',
  path: '/checkout/card-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPendingRoute = CheckoutPendingRouteImport.update({
  id: '/checkout/pending',
  path: '/checkout/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIdRoute = CompareIdRouteImport.update({
  id: '/compare/$id',
  path: '/compare/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesNewRoute = MessagesNewRouteImport.update({
  id: '/messages/new',
  path: '/messages/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopsRoute,
} as any)
const ShopsSlugRoute = ShopsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopsRoute,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdReturnRoute = OrderIdReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => OrderIdRoute,
} as any)
const ShopsCollectionsCollectionIdRoute =
  ShopsCollectionsCollectionIdRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => ShopsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/sellers': typeof SellersRoute
  '/shops': typeof ShopsRouteWithChildren
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/browse/$slug': typeof BrowseSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/card-callback': typeof CheckoutCardCallbackRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/compare/$id': typeof CompareIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/messages/$id': typeof MessagesIdRoute
  '/messages/new': typeof MessagesNewRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/order/$id/return': typeof OrderIdReturnRoute
  '/shops/collections/$collectionId': typeof ShopsCollectionsCollectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/sellers': typeof SellersRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/browse/$slug': typeof BrowseSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/card-callback': typeof CheckoutCardCallbackRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/compare/$id': typeof CompareIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/messages/$id': typeof MessagesIdRoute
  '/messages/new': typeof MessagesNewRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/categories': typeof CategoriesIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/shops': typeof ShopsIndexRoute
  '/order/$id/return': typeof OrderIdReturnRoute
  '/shops/collections/$collectionId': typeof ShopsCollectionsCollectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/sellers': typeof SellersRoute
  '/shops': typeof ShopsRouteWithChildren
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account_/addresses': typeof AccountAddressesRoute
  '/account_/settings': typeof AccountSettingsRoute
  '/account_/wishlist': typeof AccountWishlistRoute
  '/browse/$slug': typeof BrowseSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/card-callback': typeof CheckoutCardCallbackRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/compare/$id': typeof CompareIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/messages/$id': typeof MessagesIdRoute
  '/messages/new': typeof MessagesNewRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/shops/$slug': typeof ShopsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/order/$id/return': typeof OrderIdReturnRoute
  '/shops/collections/$collectionId': typeof ShopsCollectionsCollectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/contact'
    | '/delivery'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/newsletter'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sell'
    | '/sellers'
    | '/shops'
    | '/signin'
    | '/terms'
    | '/verify-email'
    | '/account/addresses'
    | '/account/settings'
    | '/account/wishlist'
    | '/browse/$slug'
    | '/categories/$slug'
    | '/checkout/card-callback'
    | '/checkout/pending'
    | '/compare/$id'
    | '/guides/$slug'
    | '/messages/$id'
    | '/messages/new'
    | '/order/$id'
    | '/product/$id'
    | '/shops/$slug'
    | '/store/$slug'
    | '/categories/'
    | '/checkout/'
    | '/guides/'
    | '/messages/'
    | '/shops/'
    | '/order/$id/return'
    | '/shops/collections/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/contact'
    | '/delivery'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/newsletter'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sell'
    | '/sellers'
    | '/signin'
    | '/terms'
    | '/verify-email'
    | '/account/addresses'
    | '/account/settings'
    | '/account/wishlist'
    | '/browse/$slug'
    | '/categories/$slug'
    | '/checkout/card-callback'
    | '/checkout/pending'
    | '/compare/$id'
    | '/guides/$slug'
    | '/messages/$id'
    | '/messages/new'
    | '/order/$id'
    | '/product/$id'
    | '/shops/$slug'
    | '/store/$slug'
    | '/categories'
    | '/checkout'
    | '/guides'
    | '/messages'
    | '/shops'
    | '/order/$id/return'
    | '/shops/collections/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/contact'
    | '/delivery'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/newsletter'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sell'
    | '/sellers'
    | '/shops'
    | '/signin'
    | '/terms'
    | '/verify-email'
    | '/account_/addresses'
    | '/account_/settings'
    | '/account_/wishlist'
    | '/browse/$slug'
    | '/categories/$slug'
    | '/checkout/card-callback'
    | '/checkout/pending'
    | '/compare/$id'
    | '/guides/$slug'
    | '/messages/$id'
    | '/messages/new'
    | '/order/$id'
    | '/product/$id'
    | '/shops/$slug'
    | '/store/$slug'
    | '/categories/'
    | '/checkout/'
    | '/guides/'
    | '/messages/'
    | '/shops/'
    | '/order/$id/return'
    | '/shops/collections/$collectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  SellersRoute: typeof SellersRoute
  ShopsRoute: typeof ShopsRouteWithChildren
  SigninRoute: typeof SigninRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  BrowseSlugRoute: typeof BrowseSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CheckoutCardCallbackRoute: typeof CheckoutCardCallbackRoute
  CheckoutPendingRoute: typeof CheckoutPendingRoute
  CompareIdRoute: typeof CompareIdRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  MessagesIdRoute: typeof MessagesIdRoute
  MessagesNewRoute: typeof MessagesNewRoute
  OrderIdRoute: typeof OrderIdRouteWithChildren
  ProductIdRoute: typeof ProductIdRoute
  StoreSlugRoute: typeof StoreSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/addresses': {
      id: '/account_/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/settings': {
      id: '/account_/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/wishlist': {
      id: '/account_/wishlist'
      path: '/account/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$slug': {
      id: '/browse/$slug'
      path: '/browse/$slug'
      fullPath: '/browse/$slug'
      preLoaderRoute: typeof BrowseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/card-callback': {
      id: '/checkout/card-callback'
      path: '/checkout/card-callback'
      fullPath: '/checkout/card-callback'
      preLoaderRoute: typeof CheckoutCardCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pending': {
      id: '/checkout/pending'
      path: '/checkout/pending'
      fullPath: '/checkout/pending'
      preLoaderRoute: typeof CheckoutPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$id': {
      id: '/compare/$id'
      path: '/compare/$id'
      fullPath: '/compare/$id'
      preLoaderRoute: typeof CompareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/new': {
      id: '/messages/new'
      path: '/messages/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof MessagesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/shops/$slug': {
      id: '/shops/$slug'
      path: '/$slug'
      fullPath: '/shops/$slug'
      preLoaderRoute: typeof ShopsSlugRouteImport
      parentRoute: typeof ShopsRoute
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id/return': {
      id: '/order/$id/return'
      path: '/return'
      fullPath: '/order/$id/return'
      preLoaderRoute: typeof OrderIdReturnRouteImport
      parentRoute: typeof OrderIdRoute
    }
    '/shops/collections/$collectionId': {
      id: '/shops/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/shops/collections/$collectionId'
      preLoaderRoute: typeof ShopsCollectionsCollectionIdRouteImport
      parentRoute: typeof ShopsRoute
    }
  }
}

interface ShopsRouteChildren {
  ShopsSlugRoute: typeof ShopsSlugRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
  ShopsCollectionsCollectionIdRoute: typeof ShopsCollectionsCollectionIdRoute
}

const ShopsRouteChildren: ShopsRouteChildren = {
  ShopsSlugRoute: ShopsSlugRoute,
  ShopsIndexRoute: ShopsIndexRoute,
  ShopsCollectionsCollectionIdRoute: ShopsCollectionsCollectionIdRoute,
}

const ShopsRouteWithChildren = ShopsRoute._addFileChildren(ShopsRouteChildren)

interface OrderIdRouteChildren {
  OrderIdReturnRoute: typeof OrderIdReturnRoute
}

const OrderIdRouteChildren: OrderIdRouteChildren = {
  OrderIdReturnRoute: OrderIdReturnRoute,
}

const OrderIdRouteWithChildren =
  OrderIdRoute._addFileChildren(OrderIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRoute,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  SellersRoute: SellersRoute,
  ShopsRoute: ShopsRouteWithChildren,
  SigninRoute: SigninRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  BrowseSlugRoute: BrowseSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CheckoutCardCallbackRoute: CheckoutCardCallbackRoute,
  CheckoutPendingRoute: CheckoutPendingRoute,
  CompareIdRoute: CompareIdRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  MessagesIdRoute: MessagesIdRoute,
  MessagesNewRoute: MessagesNewRoute,
  OrderIdRoute: OrderIdRouteWithChildren,
  ProductIdRoute: ProductIdRoute,
  StoreSlugRoute: StoreSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
