/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAppealsRouteImport } from './routes/_app/appeals'
import { Route as AppBuyerReviewsRouteImport } from './routes/_app/buyer-reviews'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppGuidesRouteImport } from './routes/_app/guides'
import { Route as AppHomepageRouteImport } from './routes/_app/homepage'
import { Route as AppListingsRouteImport } from './routes/_app/listings'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppPayoutsRouteImport } from './routes/_app/payouts'
import { Route as AppReturnsRouteImport } from './routes/_app/returns'
import { Route as AppSellersRouteImport } from './routes/_app/sellers'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppBusinessIndexRouteImport } from './routes/_app/business.index'
import { Route as AppBusinessStatementsPeriodRouteImport } from './routes/_app/business.statements.$period'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAppealsRoute = AppAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerReviewsRoute = AppBuyerReviewsRouteImport.update({
  id: '/buyer-reviews',
  path: '/buyer-reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppGuidesRoute = AppGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AppRoute,
} as any)
const AppHomepageRoute = AppHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AppRoute,
} as any)
const AppListingsRoute = AppListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoutsRoute = AppPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsRoute = AppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppSellersRoute = AppSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessIndexRoute = AppBusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessStatementsPeriodRoute =
  AppBusinessStatementsPeriodRouteImport.update({
    id: '/business/statements/$period',
    path: '/business/statements/$period',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appeals': typeof AppAppealsRoute
  '/buyer-reviews': typeof AppBuyerReviewsRoute
  '/campaigns': typeof AppCampaignsRoute
  '/categories': typeof AppCategoriesRoute
  '/guides': typeof AppGuidesRoute
  '/homepage': typeof AppHomepageRoute
  '/listings': typeof AppListingsRoute
  '/messages': typeof AppMessagesRoute
  '/orders': typeof AppOrdersRoute
  '/payouts': typeof AppPayoutsRoute
  '/returns': typeof AppReturnsRoute
  '/sellers': typeof AppSellersRoute
  '/settings': typeof AppSettingsRoute
  '/business/': typeof AppBusinessIndexRoute
  '/business/statements/$period': typeof AppBusinessStatementsPeriodRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appeals': typeof AppAppealsRoute
  '/buyer-reviews': typeof AppBuyerReviewsRoute
  '/campaigns': typeof AppCampaignsRoute
  '/categories': typeof AppCategoriesRoute
  '/guides': typeof AppGuidesRoute
  '/homepage': typeof AppHomepageRoute
  '/listings': typeof AppListingsRoute
  '/messages': typeof AppMessagesRoute
  '/orders': typeof AppOrdersRoute
  '/payouts': typeof AppPayoutsRoute
  '/returns': typeof AppReturnsRoute
  '/sellers': typeof AppSellersRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/business': typeof AppBusinessIndexRoute
  '/business/statements/$period': typeof AppBusinessStatementsPeriodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/appeals': typeof AppAppealsRoute
  '/_app/buyer-reviews': typeof AppBuyerReviewsRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/guides': typeof AppGuidesRoute
  '/_app/homepage': typeof AppHomepageRoute
  '/_app/listings': typeof AppListingsRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/payouts': typeof AppPayoutsRoute
  '/_app/returns': typeof AppReturnsRoute
  '/_app/sellers': typeof AppSellersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/business/': typeof AppBusinessIndexRoute
  '/_app/business/statements/$period': typeof AppBusinessStatementsPeriodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/appeals'
    | '/buyer-reviews'
    | '/campaigns'
    | '/categories'
    | '/guides'
    | '/homepage'
    | '/listings'
    | '/messages'
    | '/orders'
    | '/payouts'
    | '/returns'
    | '/sellers'
    | '/settings'
    | '/business/'
    | '/business/statements/$period'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/appeals'
    | '/buyer-reviews'
    | '/campaigns'
    | '/categories'
    | '/guides'
    | '/homepage'
    | '/listings'
    | '/messages'
    | '/orders'
    | '/payouts'
    | '/returns'
    | '/sellers'
    | '/settings'
    | '/'
    | '/business'
    | '/business/statements/$period'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/appeals'
    | '/_app/buyer-reviews'
    | '/_app/campaigns'
    | '/_app/categories'
    | '/_app/guides'
    | '/_app/homepage'
    | '/_app/listings'
    | '/_app/messages'
    | '/_app/orders'
    | '/_app/payouts'
    | '/_app/returns'
    | '/_app/sellers'
    | '/_app/settings'
    | '/_app/'
    | '/_app/business/'
    | '/_app/business/statements/$period'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appeals': {
      id: '/_app/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AppAppealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buyer-reviews': {
      id: '/_app/buyer-reviews'
      path: '/buyer-reviews'
      fullPath: '/buyer-reviews'
      preLoaderRoute: typeof AppBuyerReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guides': {
      id: '/_app/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof AppGuidesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/homepage': {
      id: '/_app/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof AppHomepageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listings': {
      id: '/_app/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AppListingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payouts': {
      id: '/_app/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AppPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns': {
      id: '/_app/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AppReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sellers': {
      id: '/_app/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof AppSellersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business/': {
      id: '/_app/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof AppBusinessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business/statements/$period': {
      id: '/_app/business/statements/$period'
      path: '/business/statements/$period'
      fullPath: '/business/statements/$period'
      preLoaderRoute: typeof AppBusinessStatementsPeriodRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppealsRoute: typeof AppAppealsRoute
  AppBuyerReviewsRoute: typeof AppBuyerReviewsRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppGuidesRoute: typeof AppGuidesRoute
  AppHomepageRoute: typeof AppHomepageRoute
  AppListingsRoute: typeof AppListingsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPayoutsRoute: typeof AppPayoutsRoute
  AppReturnsRoute: typeof AppReturnsRoute
  AppSellersRoute: typeof AppSellersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBusinessIndexRoute: typeof AppBusinessIndexRoute
  AppBusinessStatementsPeriodRoute: typeof AppBusinessStatementsPeriodRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppealsRoute: AppAppealsRoute,
  AppBuyerReviewsRoute: AppBuyerReviewsRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppGuidesRoute: AppGuidesRoute,
  AppHomepageRoute: AppHomepageRoute,
  AppListingsRoute: AppListingsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPayoutsRoute: AppPayoutsRoute,
  AppReturnsRoute: AppReturnsRoute,
  AppSellersRoute: AppSellersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBusinessIndexRoute: AppBusinessIndexRoute,
  AppBusinessStatementsPeriodRoute: AppBusinessStatementsPeriodRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
